baseURL = 'https://vaclavblazej.github.io/codebook/'
languageCode = 'en-us'
title = 'The Book of Code'
theme = 'simple'

[markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files

[markup]
    [markup.tableOfContents]
        startLevel = 1
        ordered = false
        endLevel = 4
